// <auto-generated />
namespace Desafio2.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AjusteNometabela : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjusteNometabela));
        
        string IMigrationMetadata.Id
        {
            get { return "202303221953039_Ajuste Nome tabela"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
